language: node_js
node_js:
    - "8"
cache:
    directories:
        - "node_modules"
script:
    - npm run build:chrome
    - npm run build:firefox
    - npm run pack:chrome
    - npm run pack:firefox
